lib/countriesweather_web/router.ex
defmodule CountriesweatherWeb.Router do
  use CountriesweatherWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CountriesweatherWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CountriesweatherWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/countries", CountryController
    get "/requests", RequestController, :index
  end

  scope "/manage", CountriesweatherWeb do
    pipe_through [:browser, :authenticate_user]
    get "/search", CountryController, :index_live
    get "/requests", RequestController, :index_live
  end

  # Other scopes may use custom stacks.
  scope "/api", CountriesweatherWeb.Api do
    pipe_through :api
    resources "/countries", CountryController, except: [:new]
    options "/countries", CountryController, :options
    resources "/requests", RequestController, except: [:new, :edit]
  end
end

lib/countriesweather_web/views/layout_view.ex
defmodule CountriesweatherWeb.LayoutView do
  use CountriesweatherWeb, :view
end

lib/countriesweather_web/templates/layout/_footer.html.eex
<footer class="w-full text-center text-gray-200 p-8 pin-b bg-indigo-900 mt-10">
  <div class="container mx-auto flex md:items-center justify-between flex-col md:flex-row py-4">
    <div class="text-left">
       <%= img_tag(Routes.static_path(@conn, "/images/cw-logo-light.svg"), class: "h-8") %>
        <p class="mt-2">
            <%= "#{Mix.env()} environment -" %> version :
            <small> <%= Application.spec(:countriesweather, :vsn) %>  </small>
       </p>
    </div>
    <ul class="text-left my-4 md:m-0 list-reset">
      <li>Read the <a href="https://gitlab.com/sbouaked/countriesweather/blob/master/README.md" class="light-text font-medium mr-4 underline">Readme</a></li>
      <li>Check out the <a href="https://gitlab.com/sbouaked/countriesweather/pipelines" class="light-text font-medium underline">Deployments Pipeline</a></li>
    </ul>
    <ul class="text-left my-4 md:m-0 list-reset">
      <li>Access to <a href="/requests" target="_blank" class="light-text font-medium mr-4 underline">Logs requests</a></li>
      <li>Check out the <a href="https://gitlab.com/sbouaked/countriesweather" target="_blank" class="light-text font-medium mr-4 underline">Gitlab Repo</a></li>
      <li>Study the <a href="https://documenter.getpostman.com/view/222453/SWDzdg2E" class="light-text font-medium mr-4 underline">API doc</a></li>
    </ul>
  </div>
</footer>

lib/countriesweather_web/templates/layout/_nav.html.eex
<nav class="container mx-auto flex items-center justify-between px-2 mt-10 md:mt-0 py-4">
    <div class="flex items-center justify-around mx-auto sm:mx-2 sm:px-4 py-4">
        <a href="/">
            <%= img_tag(Routes.static_path(@conn, "/images/cw-logo.svg"), class: "") %>
        </a>
    </div>
    <div>
        <%= if @current_user do %>
            <ul class="flex hidden md:block">
                <span class="mr-2 py-3 px-3"><%= @current_user.username %></span>
                <%= link "log out", class: "font-bold rounded py-2 px-3 hover:bg-grey-lighter", to: Routes.session_path(@conn, :delete, @current_user), method: "delete" %>
            </ul>
        <% else %>
            <ul class="flex hidden md:block">
                <li>
                    <%= link "Log in", class: "font-bold rounded py-2 px-3 hover:bg-grey-lighter", style: "line-height: 33px;", to: Routes.session_path(@conn, :new) %>
                    <%= link "Register", class: "button button-md hidden sm:inline", to: Routes.user_path(@conn, :new) %>
                </li>
            </ul>
        <% end %>
    </div>
</nav>

lib/countriesweather_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en" class="h-full">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Countriesweather</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body class="flex flex-col h-full bg-gray-100 ">
       <%= render "_nav.html" , current_user: @current_user, conn: @conn %>
       <%= if get_flash(@conn, :success) do %>
              <div id="flash" class="text-center bg-green-500 text-green-500 text-sm font-bold px-4 absolute w-full transition overflow-hidden" style="top: 91px" role="alert">
                <p class="py-3 "><%= get_flash(@conn, :success) %></p>
              </div>
       <% end %>

       <%= if get_flash(@conn, :error) do %>
              <div id="flash" class="text-center bg-red-500 text-red-100 text-sm font-bold px-4 absolute w-full transition overflow-hidden" style="top: 91px" role="alert">
                <p class="py-3 "><%= get_flash(@conn, :error) %></p>
              </div>
       <% end %>

       <main class="flex-1 mt-10 md:mt-2">
        <%= render @view_module, @view_template, assigns %>
       </main>

        <%= render("_footer.html", assigns) %>
        <script src="https://cdn.jsdelivr.net/npm/micromodal/dist/micromodal.min.js"></script>
        <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
        <script>
            (function (w,d,s,o,f,js,fjs) {
            w[o] = w[o] || function () { (w[o].q = w[o].q || []).push(arguments) };
            js = d.createElement(s), fjs = d.getElementsByTagName(s)[0];
            js.id = o; js.src = f; js.async = 1; fjs.parentNode.insertBefore(js, fjs);
            }(window, document, 'script', 'plausible', 'https://plausible.io/js/p.js'));

            plausible('page')
        </script>
  </body>
</html>