lib/countriesweather_web/router.ex
defmodule CountriesweatherWeb.Router do
  use CountriesweatherWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CountriesweatherWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CountriesweatherWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/countries", CountryController
    get "/requests", RequestController, :index
  end

  scope "/manage", CountriesweatherWeb do
    pipe_through [:browser, :authenticate_user]
    get "/search", CountryController, :index_live
    get "/requests", RequestController, :index_live
  end

  # Other scopes may use custom stacks.
  scope "/api", CountriesweatherWeb.Api do
    pipe_through :api
    resources "/countries", CountryController, except: [:new]
    options "/countries", CountryController, :options
    resources "/requests", RequestController, except: [:new, :edit]
  end
end

lib/countriesweather_web/templates/page/index.html.eex
<div>
    <div class="mt-8">
        <div class="pt-12 lg:pt-24"></div>
        <div class="container flex sm:mx-auto px-2">
            <section class="text-center sm:text-left mx-10 w-full sm:w-3/6">
                <h1 class="text-3xl lg:text-4xl font-black">
                    Need a break ?
                </h1>
                <p class="font-normal text-grey-darker text-lg lg:text-2xl mt-3 leading-tight font-medium">
                    The best app to find the best destination to go!
                </p>
                <p class="text-xs sm:text-base mr-2 font-semibold text-gray-900 mt-2">

                </p>
                <%= if @current_user do %>
                <%= link "Find a place",to: Routes.country_path(@conn, :index), class: "button button-outline w-full
                sm:w-auto mt-4 mt-6 mr-2 hover:bg-indigo-900 hover:text-white hover:border-indigo-900" %>
                <% else %>
                <%= link "Register", to: Routes.user_path(@conn, :new), class: "button w-full sm:w-auto mt-6 mr-2
                hover:bg-indigo-900 hover:text-white hover:border-indigo-900" %>
                <%= link "Find a place",to: Routes.country_path(@conn, :index), class: "button button-outline w-full
                sm:w-auto mt-4 mt-6 mr-2 hover:bg-indigo-900 hover:text-white hover:border-indigo-900" %>
                <% end %>
            </section>
            <%= if Plug.Conn.get_session(@conn, :country_id) do %>
            <section class="max-w-md mx-auto bg-white shadow-md rounded rounded-t-none border-t-2 border-indigo-500 px-8 pt-6 pb-8 w-3/6 hidden sm:block">
                <h1 class="font-black">Historic</h1>
                <div class="mt-4 border-gray-300"></div>
                <div class="flex flex-col items-center justify-between">
                    <%= for value <- Plug.Conn.get_session(@conn, :country_id) do %>
                    <%= if value != nil do %>
                    <div class="w-full flex justify-start items-center border-t py-2">
                        <span class="mr-2"><%= get_country_flag(value) %></span>
                        <%= link "#{get_country_name(value)}" , class: "hover:text-indigo-500" , to:
                        "/countries/#{value}" %>
                    </div>
                    <% end %>
                    <% end %>
                </div>
            </section>
            <% end %>
        </div>
    </div>
</div>